name: ${project.artifactId}
version: ${project.version}
author: A_W1534
main: com.addikted.immersivestream.immersiveStream
api-version: 1.18

commands:
  menu:
    description: Displays a GUI menu for Interactive Stream
    aliases: [ immersivestream, gui, imms ]
    usage: /<command>
  connecttwitch:
    description: Connects to a Twitch account
    aliases: [ connectaccount, connecttwitch, connecttwitchaccount ]
    usage: /<command> [username]
  purge:
    description: Tries to get rid of any idle players with a minigame
    aliases: [ prune]
    usage: /<command> [min] [max]