name: immersivestream
version: 0.1.0
author: A_W1534
main: com.addikted.immersivestream.immersiveStream
api-version: 1.18
commands:
  menu:
    description: Displays a GUI menu for Interactive Stream
    aliases: [ immersivestream, gui, imms ]
    usage: /<command>
  connecttwitch:
    description: Connects to a Twitch account
    aliases: [ connectaccount, connecttwitch, connecttwitchaccount ]
    usage: /<command> <username>